-- 05_unified_alert_layer.sql
-- This SQL script creates a unified alert layer by combining the results from the structuring rule (rule 1) and the velocity rule (rule 2). The resulting table `fact_alerts` includes all alerts generated by both rules, along with relevant details such as the scenario, account information, alert dates, risk scores, and labels indicating whether any laundering transactions were involved. This unified alert layer serves as a comprehensive source for downstream analysis and reporting in the BI views.
CREATE OR REPLACE TABLE fact_alerts AS
SELECT
  rule_id,
  scenario,
  from_account,
  NULL::VARCHAR AS to_account,
  NULL::BIGINT AS session_id,
  alert_date AS alert_start,
  alert_date AS alert_end,
  NULL::DOUBLE AS duration_mins,
  txn_count,
  distinct_recipients,
  risk_score,
  risk_band,
  any_laundering_txn AS label_has_laundering,
  NULL::BIGINT AS label_laundering_txns
FROM alert_cases_structuring_daily

UNION ALL

SELECT
  'RULE_2_VELOCITY' AS rule_id,
  scenario,
  from_account,
  NULL::VARCHAR AS to_account,
  session_id,
  session_start AS alert_start,
  session_end AS alert_end,
  duration_mins,
  txn_count,
  distinct_recipients,
  velocity_score AS risk_score,
  risk_band,
  session_has_laundering AS label_has_laundering,
  laundering_txn_count   AS label_laundering_txns
FROM alert_cases_velocity_banded;